<?php

namespace Database\Seeders\Tenant\Hostel;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * HstIncidentTypeSeeder
 *
 * Seeds the 6 standard incident types into sys_settings.
 * Key pattern: hostel.incident_types (stores full JSON array)
 *
 * Each incident type has:
 *   - code           : machine-readable identifier (stored in hst_incidents.incident_type)
 *   - label          : human-readable display name
 *   - severity       : default severity suggestion (can be overridden at entry)
 *   - is_auto_generated : bool — if true, system auto-creates this incident type
 *                         (e.g., absence_alert triggered by attendance service)
 *   - sort_order     : display order in dropdowns
 *
 * Copy to: database/seeders/tenant/Hostel/HstIncidentTypeSeeder.php
 */
class HstIncidentTypeSeeder extends Seeder
{
    private array $incidentTypes = [
        [
            'code'               => 'absence_alert',
            'label'              => 'Absence Alert',
            'description'        => 'Student absent without approved leave pass — auto-generated by attendance service',
            'default_severity'   => 'medium',
            'is_auto_generated'  => true,
            'sort_order'         => 1,
        ],
        [
            'code'               => 'discipline',
            'label'              => 'Discipline Issue',
            'description'        => 'Behavioral or disciplinary incident reported by warden or staff',
            'default_severity'   => 'medium',
            'is_auto_generated'  => false,
            'sort_order'         => 2,
        ],
        [
            'code'               => 'medical',
            'label'              => 'Medical Incident',
            'description'        => 'Health-related incident requiring sick bay or external medical attention',
            'default_severity'   => 'high',
            'is_auto_generated'  => false,
            'sort_order'         => 3,
        ],
        [
            'code'               => 'property_damage',
            'label'              => 'Property Damage',
            'description'        => 'Damage to hostel property, room inventory, or common areas',
            'default_severity'   => 'medium',
            'is_auto_generated'  => false,
            'sort_order'         => 4,
        ],
        [
            'code'               => 'security',
            'label'              => 'Security Incident',
            'description'        => 'Unauthorized entry, theft, or other security-related events',
            'default_severity'   => 'high',
            'is_auto_generated'  => false,
            'sort_order'         => 5,
        ],
        [
            'code'               => 'other',
            'label'              => 'Other',
            'description'        => 'General incidents not covered by the above categories',
            'default_severity'   => 'low',
            'is_auto_generated'  => false,
            'sort_order'         => 6,
        ],
    ];

    public function run(): void
    {
        DB::table('sys_settings')->upsert(
            [
                'key'         => 'hostel.incident_types',
                'value'       => json_encode($this->incidentTypes),
                'group'       => 'hostel',
                'type'        => 'json',
                'description' => 'Hostel incident type definitions with auto-generation flags',
                'is_active'   => 1,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            ['key'],
            ['value', 'updated_at']
        );

        $autoCount   = count(array_filter($this->incidentTypes, fn ($t) => $t['is_auto_generated']));
        $manualCount = count($this->incidentTypes) - $autoCount;

        $this->command->info(
            "HstIncidentTypeSeeder: seeded " . count($this->incidentTypes) .
            " incident types ({$autoCount} auto-generated, {$manualCount} manual) into sys_settings."
        );
    }
}
