<?php

namespace Modules\VisitorSecurity\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * VsmPatrolCheckpointSeeder
 *
 * Seeds 4 default campus patrol checkpoints per VSM_VisitorSecurity_Requirement.md v2 Phase 2C.
 *
 * Notes:
 *   - qr_token values are generated as UUID v4 in seeder code (NOT hardcoded strings)
 *     so each deployment gets unique tokens — prevents cross-tenant QR collision
 *   - sequence_order defines the recommended patrol route order
 *   - qr_code_path = NULL at seed time; generated by PatrolService::generateCheckpointQr()
 *     when admin prints checkpoint QR codes from the UI
 *   - created_by / updated_by = 1 (system super-admin seeder convention)
 */
class VsmPatrolCheckpointSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $checkpoints = [
            [
                'name'                 => 'Main Gate Entrance',
                'location_description' => 'Primary entry/exit gate facing the main road',
                'building'             => 'Main Building',
                'floor'                => 'Ground',
                'sequence_order'       => 1,
                'qr_token'             => (string) Str::uuid(),
                'qr_code_path'         => null,
                'is_active'            => 1,
                'created_by'           => 1,
                'updated_by'           => 1,
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'name'                 => 'Back Gate',
                'location_description' => 'Secondary entry gate at the rear boundary wall',
                'building'             => 'Back Boundary',
                'floor'                => 'Ground',
                'sequence_order'       => 2,
                'qr_token'             => (string) Str::uuid(),
                'qr_code_path'         => null,
                'is_active'            => 1,
                'created_by'           => 1,
                'updated_by'           => 1,
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'name'                 => 'Admin Block',
                'location_description' => 'Administrative block entrance; Principal and office area',
                'building'             => 'Admin Block',
                'floor'                => 'Ground',
                'sequence_order'       => 3,
                'qr_token'             => (string) Str::uuid(),
                'qr_code_path'         => null,
                'is_active'            => 1,
                'created_by'           => 1,
                'updated_by'           => 1,
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'name'                 => 'Parking Area',
                'location_description' => 'Staff and visitor parking area; outdoor zone',
                'building'             => 'Outdoor',
                'floor'                => 'Ground',
                'sequence_order'       => 4,
                'qr_token'             => (string) Str::uuid(),
                'qr_code_path'         => null,
                'is_active'            => 1,
                'created_by'           => 1,
                'updated_by'           => 1,
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
        ];

        DB::table('vsm_patrol_checkpoints')->insertOrIgnore($checkpoints);
    }
}
