<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Modules\SystemConfig\Models\Menu;

class TenantMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menus = [
            // Foundational Setup (category)
            [
                'code' => Str::slug('Foundational Setup', '_'),
                'title' => 'Foundational Setup',
                'slug' => Str::slug('Foundational Setup'),
                'description' => 'Base entities and role/session/module setup',
                'menu_for' => 'tenant',
                'icon' => 'fa-solid fa-layer-group',
                'is_category' => true,
                'parent_id' => null,
                'sort_order' => 1,
                'route' => 'dashboard.foundational-setup',
                'visible_by_default' => true,
                'permission' => '',
                'is_active' => true,
                'children' => [
                    // System Configuration
                    [
                        'code' => Str::slug('System Configuration', '_'),
                        'title' => 'System Configuration',
                        'slug' => Str::slug('System Configuration'),
                        'description' => 'Global system settings and preferences',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-sliders',
                        'is_category' => true,
                        'parent_id' => null,
                        'sort_order' => 1,
                        'route' => '',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                        'children' => [
                            [
                                'code' => Str::slug('System Settings', '_'),
                                'title' => 'System Setings',
                                'slug' => Str::slug('System Setings'),
                                'description' => 'Global system settings and preferences',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-sliders',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 1,
                                'route' => 'system-config.setting.index',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                            [
                                'code' => Str::slug('Dropdown Menus', '_'),
                                'title' => 'Dropdown Menus',
                                'slug' => Str::slug('Dropdown Menus'),
                                'description' => 'Manage reusable dropdown lists',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-list',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 2,
                                'route' => 'global-master.dropdown.index',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                            [
                                'code' => Str::slug('Media Store', '_'),
                                'title' => 'Media Store',
                                'slug' => Str::slug('Media Store'),
                                'description' => 'Manage Media',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-photo-film',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 3,
                                'route' => '',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                        ]
                    ],

                    // Roles & Permission (Prime)
                    [
                        'code' => Str::slug('Roles & Permission', '_'),
                        'title' => 'Roles & Permission',
                        'slug' => Str::slug('Roles & Permission'),
                        'description' => 'Manage roles, permissions and assignments',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-user-shield',
                        'is_category' => false,
                        'parent_id' => null,
                        'sort_order' => 2,
                        'route' => 'school-setup.user-role-prm.index',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                    ],

                    // Session & Board Setup
                    [
                        'code' => Str::slug('Session & Board Setup', '_'),
                        'title' => 'Session & Board Setup',
                        'slug' => Str::slug('Session & Board Setup'),
                        'description' => 'Configure sessions and boards',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-calendar-check',
                        'is_category' => false,
                        'parent_id' => null,
                        'sort_order' => 3,
                        'route' => 'system-config.setting.index',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                    ],
                    // Infra Setup Management
                    [
                        'code' => Str::slug('Infra. Management', '_'),
                        'title' => 'Infra. Management',
                        'slug' => Str::slug('Infra. Management'),
                        'description' => 'Create and manage Infrasetup',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-book',
                        'is_category' => false,
                        'parent_id' => null,
                        'sort_order' => 4,
                        'route' => 'school-setup.infrasetup.index',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                    ],

                ],
            ],

            // SCHOOL SETUP (category)
            [
                'code' => Str::slug('School Setup', '_'),
                'title' => 'School Setup',
                'slug' => Str::slug('School Setup'),
                'description' => 'School related entities: classes, teachers, syllabus',
                'menu_for' => 'tenant',
                'icon' => 'fa-solid fa-school',
                'is_category' => true,
                'parent_id' => null,
                'sort_order' => 2,
                'visible_by_default' => true,
                'permission' => '',
                'route' => 'dashboard.school-setup',
                'is_active' => true,
                'children' => [
                    // Core Config.
                    [
                        'code' => Str::slug('Core Config', '_'),
                        'title' => 'Core Config',
                        'slug' => Str::slug('Core Config'),
                        'description' => 'Manage Core Config',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-chalkboard',
                        'is_category' => false,
                        'parent_id' => null,
                        'sort_order' => 1,
                        'route' => '',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                        'children' => [
                            // Core Config.
                            [
                                'code' => Str::slug('Dept / Designation Mgmt.', '_'),
                                'title' => 'Dept / Designation Mgmt.',
                                'slug' => Str::slug('Dept / Designation Mgmt.'),
                                'description' => 'Manage classes, sections and subjects',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-users-rays',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 1,
                                'route' => 'school-setup.department.index',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                            // Core Config.
                            [
                                'code' => Str::slug('User Mgmt.', '_'),
                                'title' => 'User Mgmt.',
                                'slug' => Str::slug('User Mgmt.'),
                                'description' => 'Manage classes, sections and subjects',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-chalkboard',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 2,
                                'route' => 'school-setup.user.index',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                            [
                                'code' => Str::slug('Entity Group', '_'),
                                'title' => 'Entity Group',
                                'slug' => Str::slug('Entity Group'),
                                'description' => 'Manage classes, sections and subjects',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-chalkboard',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 3,
                                'route' => 'school-setup.entity-group.index',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                            [
                                'code' => Str::slug('Classification Mgmt.', '_'),
                                'title' => 'Classification Mgmt.',
                                'slug' => Str::slug('Classification Mgmt.'),
                                'description' => 'Manage classes, sections and subjects',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-indent',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 4,
                                'route' => '',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                        ]
                    ],

                    // Class & Subject Mgmt.
                    [
                        'code' => Str::slug('Staff & Student Creation', '_'),
                        'title' => 'Staff & Student Creation.',
                        'slug' => Str::slug('Staff & Student Creation'),
                        'description' => 'Manage classes, sections and subjects',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-building-user',
                        'is_category' => false,
                        'parent_id' => null,
                        'sort_order' => 2,
                        'route' => '',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                        'children' => [
                            [
                                'code' => Str::slug('Staff Mgmt.', '_'),
                                'title' => 'Staff Mgmt..',
                                'slug' => Str::slug('Staff Mgmt.'),
                                'description' => 'Manage classes, sections and subjects',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-chalkboard',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 1,
                                'route' => '',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                            [
                                'code' => Str::slug('Student Admission', '_'),
                                'title' => 'Student Admission.',
                                'slug' => Str::slug('Student Admission'),
                                'description' => 'Manage classes, sections and subjects',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-chalkboard',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 2,
                                'route' => '',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                        ]
                    ],

                    // Class & Subject Mgmt.
                    [
                        'code' => Str::slug('Class & Subject Mgmt', '_'),
                        'title' => 'Class & Subject Mgmt.',
                        'slug' => Str::slug('Class & Subject Mgmt'),
                        'description' => 'Manage classes, sections and subjects',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-chalkboard',
                        'is_category' => false,
                        'parent_id' => null,
                        'sort_order' => 3,
                        'route' => 'school-setup.school-class.index',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                    ],

                    // Teacher
                    [
                        'code' => Str::slug('Teacher', '_'),
                        'title' => 'Teacher',
                        'slug' => Str::slug('Teacher'),
                        'description' => 'Manage teacher profiles and assignments',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-user',
                        'is_category' => false,
                        'parent_id' => null,
                        'sort_order' => 4,
                        'route' => '',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                    ],

                    // Syllabus Management
                    [
                        'code' => Str::slug('Syllabus Management', '_'),
                        'title' => 'Syllabus Management',
                        'slug' => Str::slug('Syllabus Management'),
                        'description' => 'Create and manage syllabus content',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-book',
                        'is_category' => false,
                        'parent_id' => null,
                        'sort_order' => 5,
                        'route' => 'syllabus.lesson.index',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                    ],

                ],
            ],

            // Admission & Student Mgmt. (category)
            [
                'code' => Str::slug('Academic Setup', '_'),
                'title' => 'Academic Setup',
                'slug' => Str::slug('Academic Setup'),
                'description' => 'Admission workflows and student records',
                'menu_for' => 'tenant',
                'icon' => 'fa-solid fa-user-plus',
                'is_category' => true,
                'parent_id' => null,
                'sort_order' => 3,
                'visible_by_default' => true,
                'route' => 'dashboard.admission-student-management',
                'permission' => '',
                'is_active' => true,
                'children' => [

                    // Admission Mgmt.
                    [
                        'code' => Str::slug('Class & Subject Setup', '_'),
                        'title' => 'Class & Subject Setup.',
                        'slug' => Str::slug('Class & Subject Setup'),
                        'description' => 'Manage admission forms and processes',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-file-signature',
                        'is_category' => false,
                        'parent_id' => null,
                        'sort_order' => 1,
                        'route' => '',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,

                        'children' => [
                            [
                                'code' => Str::slug('Class Mgmt.', '_'),
                                'title' => 'Class Mgmt.',
                                'slug' => Str::slug('Class Mgmt.'),
                                'description' => 'Manage admission forms and processes',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-file-signature',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 1,
                                'route' => '',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                            [
                                'code' => Str::slug('Subject Mgmt', '_'),
                                'title' => 'Subject Mgmt',
                                'slug' => Str::slug('Subject Mgmt'),
                                'description' => 'Manage admission forms and processes',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-file-signature',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 2,
                                'route' => '',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],

                        ]
                    ],

                    // Admission Mgmt.
                    [
                        'code' => Str::slug('Syllabus', '_'),
                        'title' => 'Syllabus.',
                        'slug' => Str::slug('Syllabus'),
                        'description' => 'Manage admission forms and processes',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-file-signature',
                        'is_category' => false,
                        'parent_id' => null,
                        'sort_order' => 2,
                        'route' => '',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,

                        'children' => [
                            [
                                'code' => Str::slug('Syllabus Master', '_'),
                                'title' => 'Syllabus Master.',
                                'slug' => Str::slug('Syllabus Master'),
                                'description' => 'Manage admission forms and processes',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-file-signature',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 1,
                                'route' => '',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                            [
                                'code' => Str::slug('Bloom Taxonomy', '_'),
                                'title' => 'Bloom Taxonomy.',
                                'slug' => Str::slug('Bloom Taxonomy'),
                                'description' => 'Manage admission forms and processes',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-file-signature',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 2,
                                'route' => '',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                            [
                                'code' => Str::slug('Performance Config', '_'),
                                'title' => 'Performance Config.',
                                'slug' => Str::slug('Performance Config'),
                                'description' => 'Manage admission forms and processes',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-file-signature',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 3,
                                'route' => '',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                        ]
                    ],

                ],
            ],

            [
                'code' => Str::slug('Student Management', '_'),
                'title' => 'Student Management',
                'slug' => Str::slug('Student Management'),
                'description' => 'Student records, profiles and progress',
                'menu_for' => 'tenant',
                'icon' => 'fa-solid fa-user-graduate',
                'is_category' => true,
                'parent_id' => null,
                'sort_order' => 4,
                'route' => '',
                'visible_by_default' => true,
                'permission' => '',
                'is_active' => true,
                'children' => [
                    [
                        'code' => Str::slug('Student', '_'),
                        'title' => 'Student',
                        'slug' => Str::slug('Student'),
                        'description' => 'Student records, profiles and progress',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-user-graduate',
                        'is_category' => false,
                        'parent_id' => null,
                        'sort_order' => 1,
                        'route' => '',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                        'children' => [
                            [
                                'code' => Str::slug('Student Mgmt.', '_'),
                                'title' => 'Student Mgmt.',
                                'slug' => Str::slug('Student Mgmt.'),
                                'description' => 'Student records, profiles and progress',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-user-graduate',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 1,
                                'route' => '',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                            [
                                'code' => Str::slug('Mark as Alumni', '_'),
                                'title' => 'Mark as Alumni',
                                'slug' => Str::slug('Mark as Alumni'),
                                'description' => 'Student records, profiles and progress',
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-user-graduate',
                                'is_category' => false,
                                'parent_id' => null,
                                'sort_order' => 2,
                                'route' => '',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                        ]
                    ],
                ]
            ],

            // Operation Mgmt (Category)
            [
                'code' => Str::slug('Operation Mgmt', '_'),
                'title' => 'Operation Mgmt.',
                'slug' => Str::slug('Operation Mgmt'),
                'description' => 'Operational modules like transport and timetables',
                'menu_for' => 'tenant',
                'icon' => 'fa-solid fa-gear',
                'is_category' => true,
                'sort_order' => 5,
                'visible_by_default' => true,
                'permission' => '',
                'route' => 'dashboard.operation-management',
                'is_active' => true,
                'children' => [

                    // Transport Management
                    [
                        'code' => Str::slug('Transport Management', '_'),
                        'title' => 'Transport Management',
                        'slug' => Str::slug('Transport Management'),
                        'description' => 'Manage transport, routes and vehicles',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-bus',
                        'is_category' => true,
                        'sort_order' => 1,
                        'route' => 'transport.transport-master.index',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,

                        'children' => [

                            [
                                'code' => Str::slug('Transport Master', '_'),
                                'title' => 'Transport Master',
                                'slug' => Str::slug('Transport Master'),
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-route',
                                'is_category' => false,
                                'sort_order' => 1,
                                'route' => 'transport.transport-master.index',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],

                            [
                                'code' => Str::slug('Vehicle Mgmt', '_'),
                                'title' => 'Vehicle Mgmt',
                                'slug' => Str::slug('Vehicle Mgmt'),
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-truck',
                                'is_category' => false,
                                'sort_order' => 2,
                                'route' => 'transport.vehicle-mgmt.index',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],

                            [
                                'code' => Str::slug('Staff Attendance', '_'),
                                'title' => 'Staff Attendance',
                                'slug' => Str::slug('Staff Attendance'),
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-users',
                                'is_category' => false,
                                'sort_order' => 3,
                                'route' => 'transport.staff-mgmt.index',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],

                            [
                                'code' => Str::slug('Trip Management', '_'),
                                'title' => 'Trip Management',
                                'slug' => Str::slug('Trip Management'),
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-map-location-dot',
                                'is_category' => false,
                                'sort_order' => 4,
                                'route' => 'transport.trip-management.index',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],

                            [
                                'code' => Str::slug('Student Tranport Mgmt.', '_'),
                                'title' => 'Student Tranport Mgmt.',
                                'slug' => Str::slug('Student Tranport Mgmt.'),
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-money-check',
                                'is_category' => false,
                                'sort_order' => 5,
                                'route' => 'transport.std-route-Fees-mgmt.index',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],

                            [
                                'code' => Str::slug('Transport Notification', '_'),
                                'title' => 'Transport Notification',
                                'slug' => Str::slug('Transport Notification'),
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-chart-line',
                                'is_category' => false,
                                'sort_order' => 6,
                                'route' => 'transport.transport-report.index',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                        ],
                    ],

                    // Timetable Management
                    [
                        'code' => Str::slug('Timetable Management', '_'),
                        'title' => 'Timetable Management',
                        'slug' => Str::slug('Timetable Management'),
                        'description' => 'Create and manage timetables',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-calendar-days',
                        'is_category' => false,
                        'sort_order' => 2,
                        'route' => 'smart-timetable.smart-timetable-management.index',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                        'children' => [
                            [
                                'code' => Str::slug('Timetable Master', '_'),
                                'title' => 'Timetable Master',
                                'slug' => Str::slug('Timetable Master'),
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-book',
                                'is_category' => false,
                                'sort_order' => 1,
                                'route' => 'smart-timetable.timetable.timetableMaster',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],

                            [
                                'code' => Str::slug('Timetable Operation', '_'),
                                'title' => 'Timetable Operation',
                                'slug' => Str::slug('Timetable Operation'),
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-clock-rotate-left',
                                'is_category' => false,
                                'sort_order' => 2,
                                'route' => 'smart-timetable.timetable.timetableOperation',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],

                            [
                                'code' => Str::slug('Timetable Generation', '_'),
                                'title' => 'Timetable Generation & Logs',
                                'slug' => Str::slug('Timetable Generation'),
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-gears',
                                'is_category' => false,
                                'sort_order' => 3,
                                'route' => 'smart-timetable.timetable.timetableGeneration',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],

                            [
                                'code' => Str::slug('Timetable Reports', '_'),
                                'title' => 'Timetable Reports',
                                'slug' => Str::slug('Timetable Reports'),
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-chart-column',
                                'is_category' => false,
                                'sort_order' => 4,
                                'route' => 'smart-timetable.timetable.timetableReports',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                            [
                                'code' => Str::slug('Timetable Config', '_'),
                                'title' => 'Timetable Config',
                                'slug' => Str::slug('Timetable Config'),
                                'menu_for' => 'tenant',
                                'icon' => 'fa-solid fa-wrench',
                                'is_category' => false,
                                'sort_order' => 5,
                                'route' => 'smart-timetable.timetable.timetableConfig',
                                'visible_by_default' => true,
                                'permission' => '',
                                'is_active' => true,
                            ],
                        ],
                    ],
                ],
            ],
            [
                'code' => Str::slug('Front Desk', '_'),
                'title' => 'Front Desk',
                'slug' => Str::slug('Front Desk'),
                'description' => 'Operational modules like transport and timetables',
                'menu_for' => 'tenant',
                'icon' => 'fa-solid fa-gear',
                'is_category' => true,
                'sort_order' => 6,
                'visible_by_default' => true,
                'permission' => '',
                'route' => 'dashboard.operation-management',
                'is_active' => true,

                'children' => [

                    // Transport Management
                    [
                        'code' => Str::slug('Notification', '_'),
                        'title' => 'Notification',
                        'slug' => Str::slug('Notification'),
                        'description' => 'Manage transport, routes and vehicles',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-bus',
                        'is_category' => true,
                        'sort_order' => 1,
                        'route' => 'transport.transport-master.index',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                    ],

                    // Timetable Management
                    [
                        'code' => Str::slug('Admission', '_'),
                        'title' => 'Admission',
                        'slug' => Str::slug('Admission'),
                        'description' => 'Create and manage timetables',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-clock',
                        'is_category' => false,
                        'sort_order' => 2,
                        'route' => '',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                        'children' =>
                            [
                                [
                                    'code' => Str::slug('Admission Enquiry', '_'),
                                    'title' => 'Admission Enquiry',
                                    'slug' => Str::slug('Admission Enquiry'),
                                    'description' => 'Create and manage timetables',
                                    'menu_for' => 'tenant',
                                    'icon' => 'fa-solid fa-clock',
                                    'is_category' => false,
                                    'sort_order' => 1,
                                    'route' => '',
                                    'visible_by_default' => true,
                                    'permission' => '',
                                    'is_active' => true,
                                ],
                            ]
                    ],
                ],

            ],
            [
                'code' => Str::slug('Support', '_'),
                'title' => 'Support',
                'slug' => Str::slug('Support'),
                'description' => 'Support modules like Complaints and timetables',
                'menu_for' => 'tenant',
                'icon' => 'fa-solid fa-clipboard-list',
                'is_category' => true,
                'sort_order' => 7,
                'visible_by_default' => true,
                'permission' => '',
                'route' => 'dashboard.support-management',
                'is_active' => true,

                'children' => [

                    // Complaints Management
                    [
                        'code' => Str::slug('Complaint Mgmt.', '_'),
                        'title' => 'Complaint Mgmt.',
                        'slug' => Str::slug('Complaint Mgmt.'),
                        'description' => 'Manage Complaints',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-envelopes-bulk',
                        'is_category' => true,
                        'sort_order' => 1,
                        'route' => 'complaint.complaint-mgt.index',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                    ],

                    // Audit Log Management
                    [
                        'code' => Str::slug('Audit Log', '_'),
                        'title' => 'Audit Log',
                        'slug' => Str::slug('Audit Log'),
                        'description' => 'Create and manage timetables',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-clock',
                        'is_category' => false,
                        'sort_order' => 2,
                        'route' => '',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                        'children' =>
                            [
                                [
                                    'code' => Str::slug('Vew Activities', '_'),
                                    'title' => 'Vew Activities',
                                    'slug' => Str::slug('Vew Activities'),
                                    'description' => 'Create and manage timetables',
                                    'menu_for' => 'tenant',
                                    'icon' => 'fa-solid fa-clock',
                                    'is_category' => false,
                                    'sort_order' => 1,
                                    'route' => '',
                                    'visible_by_default' => true,
                                    'permission' => '',
                                    'is_active' => true,
                                ],
                            ]
                    ],
                    [
                        'code' => Str::slug('Help (Doc / Videos)', '_'),
                        'title' => 'Help (Doc / Videos)',
                        'slug' => Str::slug('Help (Doc / Videos)'),
                        'description' => 'Manage transport, routes and vehicles',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-bus',
                        'is_category' => true,
                        'sort_order' => 3,
                        'route' => '',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                    ],
                    [
                        'code' => Str::slug('Register App Bug', '_'),
                        'title' => 'Register App Bug',
                        'slug' => Str::slug('Register App Bug'),
                        'description' => 'Manage transport, routes and vehicles',
                        'menu_for' => 'tenant',
                        'icon' => 'fa-solid fa-bus',
                        'is_category' => true,
                        'sort_order' => 4,
                        'route' => '',
                        'visible_by_default' => true,
                        'permission' => '',
                        'is_active' => true,
                    ],
                ],
            ]
        ];
        foreach ($menus as $menu) {
            $this->seedMenu($menu);
        }
    }
    private function seedMenu(array $menuData, $parentId = null)
    {
        $children = $menuData['children'] ?? [];
        unset($menuData['children']);

        // Enforce DB rule automatically
        // if ($menuData['is_category']) {
        //     $menuData['route'] = null;
        // }

        $menu = Menu::updateOrCreate(
            [
                'code' => $menuData['code'],
                'menu_for' => $menuData['menu_for'],
            ],
            array_merge($menuData, [
                'parent_id' => $parentId,
            ])
        );

        foreach ($children as $child) {
            $this->seedMenu($child, $menu->id);
        }
    }
}