-- =========================================================================
-- LMS QUIZ & QUEST MODULE DDL v1.0
-- Technologies: MySQL 8.x, Laravel 10.x
-- Dependencies: qns_questions_bank, slb_topics, sys_users, sch_students
-- =========================================================================

-- =========================================================================
-- 3. QUEST MODULE
-- =========================================================================
-- Master files exists in LMS_Quiz will be used here also
-- lms_difficulty_distribution_configs
-- lms_difficulty_distribution_details
-- lms_assessment_types

-- -------------------------------------------------------------------------------------------------------
-- Screen File name - LMS Quest     Tab-1 (Name - Quests)
-- -------------------------------------------------------------------------------------------------------

-- Main Quest Table
CREATE TABLE IF NOT EXISTS `lms_quests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `academic_session_id` BIGINT UNSIGNED NOT NULL,   -- FK to glb_academic_sessions.id
  `class_id` BIGINT UNSIGNED NOT NULL,              -- FK to sch_classes.id
  `subject_id` BIGINT UNSIGNED NOT NULL,            -- FK to sch_subjects.id
  `quest_type_id` BIGINT UNSIGNED NOT NULL,  -- FK to lms_assessment_types.id (e.g. 'Challenge', 'Enrichment', 'Practice', 'Revision', 'Re-Test', 'Diagnostic', 'Remedial')
  `quest_code` VARCHAR(50) NOT NULL,  -- Auto Generated (e.g. 'QUEST_9TH_SCI_L01_SUB08_EASY', 'QUEST_9TH_SCI_L01_SUB08_BALANCED', 'QUEST_9TH_SCI_L01_SUB08_DIFFICULT')
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT DEFAULT NULL,
  `instructions` TEXT DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  -- Settings
  `duration_minutes` INT UNSIGNED DEFAULT NULL,
  `total_marks` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `total_questions` INT UNSIGNED NOT NULL DEFAULT 0,
  `passing_percentage` DECIMAL(5,2) NOT NULL DEFAULT 33.00,
  `allow_multiple_attempts` TINYINT(1) NOT NULL DEFAULT 0,
  `max_attempts` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `negative_marks` DECIMAL(4,2) NOT NULL DEFAULT 0.00, -- e.g. 0.25  (If Negative Marking Factor is zero then no negative marks will be given)
  `is_randomized` TINYINT(1) NOT NULL DEFAULT 0,  -- Randomize Questions (If this will be 1 then questions will be randomized)
  `question_marks_shown` TINYINT(1) NOT NULL DEFAULT 0, -- Show Question Marks (If this will be 1 then Question Marks will be shown when attempt to the quiz)
  `auto_publish_result` TINYINT(1) NOT NULL DEFAULT 0,  -- Auto Publish Result (Result of the Class will be shown Automatically just after due date)
  `timer_enforced` TINYINT(1) NOT NULL DEFAULT 1,  -- Enforce Timer (If Timer is enforced then timer will be shown)
  `show_correct_answer` TINYINT(1) NOT NULL DEFAULT 0, -- Show Correct Answer (If this will be 1 then Correct Answer will be shown when attempt to the quiz)
  `show_explanation` TINYINT(1) NOT NULL DEFAULT 0, -- Show Explanation (If this will be 1 then Explanation will be shown when attempt to the quiz)
  `difficulty_config_id` BIGINT UNSIGNED DEFAULT NULL,  -- FK to lms_difficulty_distribution_configs
  `ignore_difficulty_config` TINYINT(1) NOT NULL DEFAULT 0, -- Ignore Difficulty Config (If this will be 1 then difficulty_config_id will be ignored)
  `is_system_generated` TINYINT(1) NOT NULL DEFAULT 0,  -- System Generated (If this will be 1 then quest will be generated by the system)
  `only_unused_questions` TINYINT(1) NOT NULL DEFAULT 0, -- Only Unused Questions (Question should not be in qns_question_usage_log)
  `only_authorised_questions` TINYINT(1) NOT NULL DEFAULT 0, -- If this will be 1 then use only questions where qns_questions_bank.for_quiz = 1
  -- Audit
  `created_by` BIGINT UNSIGNED DEFAULT NULL,  -- FK to sys_users
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_quest_uuid` (`uuid`),
  UNIQUE KEY `uq_quest_code` (`quest_code`),
  CONSTRAINT `fk_quest_academic_session` FOREIGN KEY (`academic_session_id`) REFERENCES `glb_academic_sessions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_quest_class` FOREIGN KEY (`class_id`) REFERENCES `sch_classes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_quest_subject` FOREIGN KEY (`subject_id`) REFERENCES `sch_subjects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_quest_type` FOREIGN KEY (`quest_type_id`) REFERENCES `lms_assessment_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_quest_diff` FOREIGN KEY (`difficulty_config_id`) REFERENCES `lms_difficulty_distribution_configs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_quest_creator` FOREIGN KEY (`created_by`) REFERENCES `sys_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------------------------------------------------
-- Screen File name - LMS Quest     Tab-2 (Name - Quest Scopes)
-- -------------------------------------------------------------------------------------------------------
-- Scope needs to be covered separately as Quest may cover Multipal Lesson, Topics, Sub-Topics.
-- Quest Scopes (Topics covered)
CREATE TABLE IF NOT EXISTS `lms_quest_scopes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quest_id` BIGINT UNSIGNED NOT NULL,              -- FK to lms_quests.id
  `lesson_id` BIGINT UNSIGNED NOT NULL,             -- FK to slb_lessons.id
  `topic_id` BIGINT UNSIGNED NOT NULL,              -- FK to slb_topics.id
  `question_type_id` INT UNSIGNED DEFAULT NULL,     -- FK to qns_question_types.id (e.g. MCQs, True/False, Fill in the Blanks, etc.)
  `target_question_count` INT UNSIGNED DEFAULT 0,   -- Target Question Count (If this will be 0 then all the questions of the topic will be included)
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_qs_quest` FOREIGN KEY (`quest_id`) REFERENCES `lms_quests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_qs_topic` FOREIGN KEY (`topic_id`) REFERENCES `slb_topics` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_qs_lesson` FOREIGN KEY (`lesson_id`) REFERENCES `slb_lessons` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------------------------------------------------
-- Screen File name - LMS Quest     Tab-3 (Name - Add Questions to Quest)
-- -------------------------------------------------------------------------------------------------------
-- Quest Questions (Junction)
CREATE TABLE IF NOT EXISTS `lms_quest_questions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quest_id` BIGINT UNSIGNED NOT NULL,              -- FK to lms_quests.id
  `question_id` BIGINT UNSIGNED NOT NULL,           -- FK to qns_questions.id
  `ordinal` INT UNSIGNED NOT NULL DEFAULT 0,
  `marks_override` DECIMAL(5,2) DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_quest_ques` (`quest_id`, `question_id`),
  CONSTRAINT `fk_qst_q_quest` FOREIGN KEY (`quest_id`) REFERENCES `lms_quests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_qst_q_question` FOREIGN KEY (`question_id`) REFERENCES `qns_questions_bank` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------------------------------------------------
-- Screen File name - LMS Quest     Tab-4 (Name - Assign Quest to Students)
-- -------------------------------------------------------------------------------------------------------
-- Quest Allocations
CREATE TABLE IF NOT EXISTS `lms_quest_allocations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quest_id` BIGINT UNSIGNED NOT NULL,
  `allocation_type` ENUM('CLASS','SECTION','GROUP','STUDENT') NOT NULL,
  `target_table_name` VARCHAR(60) NOT NULL,        -- Name of the target table (e.g. 'sch_classes', 'sch_sections', 'sch_entity_groups', 'std_students')
  `target_id` BIGINT UNSIGNED NOT NULL,             -- ID of Class, Section, Group, or Student (e.g. sch_classes.id, sch_sections.id, sch_entity_groups.id, std_students.id)
  `assigned_by` BIGINT UNSIGNED DEFAULT NULL,       -- FK to sys_users.id (Who assigned the quest). Null if assigned by System
  -- Timing
  `published_at` DATETIME DEFAULT NULL,
  `due_date` DATETIME DEFAULT NULL,
  `cut_off_date` DATETIME DEFAULT NULL,             -- No submissions after
  `is_auto_publish_result` TINYINT(1) NOT NULL DEFAULT 0, -- Auto Publish Result (Result of the Class will be shown Automatically just after due date)
  `result_publish_date` DATETIME DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_quest_alloc_target` (`allocation_type`, `target_id`),
  CONSTRAINT `fk_qsta_quest` FOREIGN KEY (`quest_id`) REFERENCES `lms_quests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_qsta_assigner` FOREIGN KEY (`assigned_by`) REFERENCES `sys_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




-- =========================================================================
-- 5. SEED DATA
-- =========================================================================

-- Seed Dropdown Needs
INSERT INTO `sys_dropdown_needs` 
(`db_type`, `table_name`, `column_name`, `menu_category`, `main_menu`, `sub_menu`, `field_name`, `is_system`, `tenant_creation_allowed`) 
VALUES 
('Tenant', 'lms_quizzes', 'quiz_type_id', 'LMS', 'Quiz Management', 'Quiz Setup', 'Quiz Type', 1, 1),
('Tenant', 'lms_quests', 'quest_type_id', 'LMS', 'Quest Management', 'Quest Setup', 'Quest Type', 1, 1);

-- Get IDs for insertion (Assuming standard flow, but using subqueries for safety in script if possible or placeholder)
-- Since we can't use variables easily in a single script without procedure, we assume usage of IDs 1001, 1002 for the example or just Insert Values.
-- Note: In a real migration, we fetch IDs. Here we provide INSERT statements for `sys_dropdown_table`.

-- Quiz Types
SET @need_id_quiz = (SELECT id FROM sys_dropdown_needs WHERE table_name = 'lms_quizzes' AND column_name = 'quiz_type_id' LIMIT 1);
INSERT INTO `sys_dropdown_table` (`dropdown_needs_id`, `ordinal`, `key`, `value`, `is_active`) VALUES
(@need_id_quiz, 1, 'FORMATIVE', 'Formative Assessment', 1),
(@need_id_quiz, 2, 'SUMMATIVE', 'Summative Assessment', 1),
(@need_id_quiz, 3, 'DIAGNOSTIC', 'Diagnostic Assessment', 1),
(@need_id_quiz, 4, 'PRACTICE', 'Practice Quiz', 1);

-- Quest Types
SET @need_id_quest = (SELECT id FROM sys_dropdown_needs WHERE table_name = 'lms_quests' AND column_name = 'quest_type_id' LIMIT 1);
INSERT INTO `sys_dropdown_table` (`dropdown_needs_id`, `ordinal`, `key`, `value`, `is_active`) VALUES
(@need_id_quest, 1, 'LEARNING_PATH', 'Learning Path Quest', 1),
(@need_id_quest, 2, 'PROJECT_BASED', 'Project Based Quest', 1),
(@need_id_quest, 3, 'MASTER_CHALLENGE', 'Mastery Challenge', 1);

-- Sample Difficulty Config
INSERT INTO `lms_difficulty_distribution_configs` (`code`, `name`, `used_for`, `description`) VALUES
('STD_BALANCED_QUIZ', 'Standard Balanced Quiz', 'QUIZ', '30% Easy, 50% Medium, 20% Hard');


-- ---------------------------------------------------------------------------------------------------------------------
-- Changes :
-- 1. Added `lesson_id` column to `lms_quests` table to align with the lesson plan. 
-- TABLE lms_quests - ADDED -
--        `academic_session_id` BIGINT UNSIGNED NOT NULL,   -- FK to academic_sessions.id
--        `class_id` BIGINT UNSIGNED NOT NULL,              -- FK to sch_classes.id
--        `subject_id` BIGINT UNSIGNED NOT NULL,            -- FK to sch_subjects.id
--        `lesson_id` BIGINT UNSIGNED NOT NULL,             -- FK to sch_lessons.id
--        `quest_code` - AUTO GENERATED code e.g. 'QUEST_9TH_SCI_L01_SUB08_EASY' (QUEST+Class Code+Subject Code+Lesson Code+Topic Code+quest_type(lms_assessment_types.code))
